## <center> Numpy Assignment</center>

In [1]:
# importing req. packages
import numpy as np

- Problem Statement 1: 
  - Write a function so that the columns of the output matrix are powers of the input vector. 
  - The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
  - HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

In [2]:
# numpy has its own method for generating this kind of metrix.

# input_vector = np.array([1,3,5,7])
# print(np.vander(input_vector))
# print(np.vander(input_vector, 5))
#np.vander(input_vector,increasing=True)

### creating custom vendor method which will work like vander method

In [3]:
def custom_vander(input_vector, N=None, increasing=False):
    '''
        this function acts like vander function of numpy.
        It takes 3 parameters:-
        x : array_like 1-D input array.
        N : int, optional 
            Number of columns in the output.  
            If `N` is not specified, a square array is returned (``N = len(x)``).
        increasing : bool, optional
            Order of the powers of the columns.  If True, the powers increase from left to right, if False (the default) they are reversed.
    '''
    
    
    if N == None:
        N = len(input_vector)
    output_matrix = np.zeros(shape=(len(input_vector), N))
    if increasing == True:
        for i in range(0,N):
            output_matrix[:,i] = input_vector ** (i)
    else:
        for i in range(0,N):
            output_matrix[:,i] = input_vector ** (N-1-i)  
    return output_matrix
    

In [4]:
ans = custom_vander(np.array([1,3,5,7]))
ans

array([[  1.,   1.,   1.,   1.],
       [ 27.,   9.,   3.,   1.],
       [125.,  25.,   5.,   1.],
       [343.,  49.,   7.,   1.]])

In [5]:
ans = custom_vander(np.array([1,3,5,7]),3)
ans

array([[ 1.,  1.,  1.],
       [ 9.,  3.,  1.],
       [25.,  5.,  1.],
       [49.,  7.,  1.]])

In [6]:
ans = custom_vander(np.array([1,3,5,7]), increasing=True)
ans

array([[  1.,   1.,   1.,   1.],
       [  1.,   3.,   9.,  27.],
       [  1.,   5.,  25., 125.],
       [  1.,   7.,  49., 343.]])

- Problem Statement 2: 
  - Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
  - The moving average sequence has n-k+1 elements as shown below. 
  - The moving averages with k=4 of a ten-value sequence (n=10) is shown below <br>

In [7]:
def find_moving_avg(input_value, k):
    '''
        this method takes 2 parameters:-
        input_value : a sequence consisting of 1D list or numpy array.
        k : k-th moving average of the given sequence, integer value.
    '''
    
    # if list is passed changing it into numpy array
    if(type(input_value) == list):
        input_value = np.array(input_value)
    
    # finding value of moving avg seq number i.e, n-k+1
    moving_avg_seq_elements = len(input_value)-k+1
    
    # preparing output string as per specified in the question.
    for i in range(moving_avg_seq_elements):
        
        # calculating moving avg and rounding off to 2 decimal places
        moving_avg = format(input_value[i:i+k].sum()/k, '.2f') 
        
        # preparing string as -> y1 25 = (10+20+30+40)/4
        output_string = f"y{i+1} {moving_avg} = ("
        for x in range(k):
            if x == k-1:
                output_string += f"{input_value[x+i]}"
            else:
                output_string += f"{input_value[x+i]}+"
                
        output_string += f")/{k}"
        
        print(output_string)
    

In [8]:
find_moving_avg(list(range(10,101,10)), 4)

y1 25.00 = (10+20+30+40)/4
y2 35.00 = (20+30+40+50)/4
y3 45.00 = (30+40+50+60)/4
y4 55.00 = (40+50+60+70)/4
y5 65.00 = (50+60+70+80)/4
y6 75.00 = (60+70+80+90)/4
y7 85.00 = (70+80+90+100)/4


In [9]:
find_moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

y1 5.00 = (3+5+7)/3
y2 4.67 = (5+7+2)/3
y3 5.67 = (7+2+8)/3
y4 6.67 = (2+8+10)/3
y5 9.67 = (8+10+11)/3
y6 28.67 = (10+11+65)/3
y7 49.33 = (11+65+72)/3
y8 72.67 = (65+72+81)/3
y9 84.00 = (72+81+99)/3
y10 93.33 = (81+99+100)/3
y11 116.33 = (99+100+150)/3
